// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Packet.proto

#include "grSim_Packet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR grSim_Packet::grSim_Packet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.commands_)*/nullptr
  , /*decltype(_impl_.replacement_)*/nullptr} {}
struct grSim_PacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR grSim_PacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~grSim_PacketDefaultTypeInternal() {}
  union {
    grSim_Packet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 grSim_PacketDefaultTypeInternal _grSim_Packet_default_instance_;
static ::_pb::Metadata file_level_metadata_grSim_5fPacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_grSim_5fPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_grSim_5fPacket_2eproto = nullptr;

const uint32_t TableStruct_grSim_5fPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::grSim_Packet, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::grSim_Packet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::grSim_Packet, _impl_.commands_),
  PROTOBUF_FIELD_OFFSET(::grSim_Packet, _impl_.replacement_),
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::grSim_Packet)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_grSim_Packet_default_instance_._instance,
};

const char descriptor_table_protodef_grSim_5fPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022grSim_Packet.proto\032\024grSim_Commands.pro"
  "to\032\027grSim_Replacement.proto\"Z\n\014grSim_Pac"
  "ket\022!\n\010commands\030\001 \001(\0132\017.grSim_Commands\022\'"
  "\n\013replacement\030\002 \001(\0132\022.grSim_ReplacementB"
  "-Z+github.com/Rione-SSL/RACOON-Pi/proto/"
  "pb_gen"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_grSim_5fPacket_2eproto_deps[2] = {
  &::descriptor_table_grSim_5fCommands_2eproto,
  &::descriptor_table_grSim_5fReplacement_2eproto,
};
static ::_pbi::once_flag descriptor_table_grSim_5fPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_grSim_5fPacket_2eproto = {
    false, false, 206, descriptor_table_protodef_grSim_5fPacket_2eproto,
    "grSim_Packet.proto",
    &descriptor_table_grSim_5fPacket_2eproto_once, descriptor_table_grSim_5fPacket_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_grSim_5fPacket_2eproto::offsets,
    file_level_metadata_grSim_5fPacket_2eproto, file_level_enum_descriptors_grSim_5fPacket_2eproto,
    file_level_service_descriptors_grSim_5fPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_grSim_5fPacket_2eproto_getter() {
  return &descriptor_table_grSim_5fPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_grSim_5fPacket_2eproto(&descriptor_table_grSim_5fPacket_2eproto);

// ===================================================================

class grSim_Packet::_Internal {
 public:
  using HasBits = decltype(std::declval<grSim_Packet>()._impl_._has_bits_);
  static const ::grSim_Commands& commands(const grSim_Packet* msg);
  static void set_has_commands(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::grSim_Replacement& replacement(const grSim_Packet* msg);
  static void set_has_replacement(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::grSim_Commands&
grSim_Packet::_Internal::commands(const grSim_Packet* msg) {
  return *msg->_impl_.commands_;
}
const ::grSim_Replacement&
grSim_Packet::_Internal::replacement(const grSim_Packet* msg) {
  return *msg->_impl_.replacement_;
}
void grSim_Packet::clear_commands() {
  if (_impl_.commands_ != nullptr) _impl_.commands_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void grSim_Packet::clear_replacement() {
  if (_impl_.replacement_ != nullptr) _impl_.replacement_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
grSim_Packet::grSim_Packet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:grSim_Packet)
}
grSim_Packet::grSim_Packet(const grSim_Packet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  grSim_Packet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.commands_){nullptr}
    , decltype(_impl_.replacement_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_commands()) {
    _this->_impl_.commands_ = new ::grSim_Commands(*from._impl_.commands_);
  }
  if (from._internal_has_replacement()) {
    _this->_impl_.replacement_ = new ::grSim_Replacement(*from._impl_.replacement_);
  }
  // @@protoc_insertion_point(copy_constructor:grSim_Packet)
}

inline void grSim_Packet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.commands_){nullptr}
    , decltype(_impl_.replacement_){nullptr}
  };
}

grSim_Packet::~grSim_Packet() {
  // @@protoc_insertion_point(destructor:grSim_Packet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void grSim_Packet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.commands_;
  if (this != internal_default_instance()) delete _impl_.replacement_;
}

void grSim_Packet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void grSim_Packet::Clear() {
// @@protoc_insertion_point(message_clear_start:grSim_Packet)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(_impl_.commands_ != nullptr);
      _impl_.commands_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.replacement_ != nullptr);
      _impl_.replacement_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* grSim_Packet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .grSim_Commands commands = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_commands(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .grSim_Replacement replacement = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_replacement(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* grSim_Packet::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:grSim_Packet)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .grSim_Commands commands = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::commands(this),
        _Internal::commands(this).GetCachedSize(), target, stream);
  }

  // optional .grSim_Replacement replacement = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::replacement(this),
        _Internal::replacement(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grSim_Packet)
  return target;
}

size_t grSim_Packet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:grSim_Packet)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .grSim_Commands commands = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.commands_);
    }

    // optional .grSim_Replacement replacement = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.replacement_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData grSim_Packet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    grSim_Packet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*grSim_Packet::GetClassData() const { return &_class_data_; }


void grSim_Packet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<grSim_Packet*>(&to_msg);
  auto& from = static_cast<const grSim_Packet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grSim_Packet)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_commands()->::grSim_Commands::MergeFrom(
          from._internal_commands());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_replacement()->::grSim_Replacement::MergeFrom(
          from._internal_replacement());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void grSim_Packet::CopyFrom(const grSim_Packet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grSim_Packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool grSim_Packet::IsInitialized() const {
  if (_internal_has_commands()) {
    if (!_impl_.commands_->IsInitialized()) return false;
  }
  if (_internal_has_replacement()) {
    if (!_impl_.replacement_->IsInitialized()) return false;
  }
  return true;
}

void grSim_Packet::InternalSwap(grSim_Packet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(grSim_Packet, _impl_.replacement_)
      + sizeof(grSim_Packet::_impl_.replacement_)
      - PROTOBUF_FIELD_OFFSET(grSim_Packet, _impl_.commands_)>(
          reinterpret_cast<char*>(&_impl_.commands_),
          reinterpret_cast<char*>(&other->_impl_.commands_));
}

::PROTOBUF_NAMESPACE_ID::Metadata grSim_Packet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_grSim_5fPacket_2eproto_getter, &descriptor_table_grSim_5fPacket_2eproto_once,
      file_level_metadata_grSim_5fPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::grSim_Packet*
Arena::CreateMaybeMessage< ::grSim_Packet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::grSim_Packet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
