// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_gc_common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ssl_5fgc_5fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ssl_5fgc_5fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ssl_5fgc_5fcommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ssl_5fgc_5fcommon_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ssl_5fgc_5fcommon_2eproto;
class RobotId;
struct RobotIdDefaultTypeInternal;
extern RobotIdDefaultTypeInternal _RobotId_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RobotId* Arena::CreateMaybeMessage<::RobotId>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Team : int {
  UNKNOWN = 0,
  YELLOW = 1,
  BLUE = 2
};
bool Team_IsValid(int value);
constexpr Team Team_MIN = UNKNOWN;
constexpr Team Team_MAX = BLUE;
constexpr int Team_ARRAYSIZE = Team_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Team_descriptor();
template<typename T>
inline const std::string& Team_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Team>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Team_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Team_descriptor(), enum_t_value);
}
inline bool Team_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Team* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Team>(
    Team_descriptor(), name, value);
}
enum Division : int {
  DIV_UNKNOWN = 0,
  DIV_A = 1,
  DIV_B = 2
};
bool Division_IsValid(int value);
constexpr Division Division_MIN = DIV_UNKNOWN;
constexpr Division Division_MAX = DIV_B;
constexpr int Division_ARRAYSIZE = Division_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Division_descriptor();
template<typename T>
inline const std::string& Division_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Division>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Division_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Division_descriptor(), enum_t_value);
}
inline bool Division_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Division* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Division>(
    Division_descriptor(), name, value);
}
// ===================================================================

class RobotId final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RobotId) */ {
 public:
  inline RobotId() : RobotId(nullptr) {}
  ~RobotId() override;
  explicit PROTOBUF_CONSTEXPR RobotId(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RobotId(const RobotId& from);
  RobotId(RobotId&& from) noexcept
    : RobotId() {
    *this = ::std::move(from);
  }

  inline RobotId& operator=(const RobotId& from) {
    CopyFrom(from);
    return *this;
  }
  inline RobotId& operator=(RobotId&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RobotId& default_instance() {
    return *internal_default_instance();
  }
  static inline const RobotId* internal_default_instance() {
    return reinterpret_cast<const RobotId*>(
               &_RobotId_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RobotId& a, RobotId& b) {
    a.Swap(&b);
  }
  inline void Swap(RobotId* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RobotId* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RobotId* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RobotId>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RobotId& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RobotId& from) {
    RobotId::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotId* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RobotId";
  }
  protected:
  explicit RobotId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kTeamFieldNumber = 2,
  };
  // optional uint32 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // optional .Team team = 2;
  bool has_team() const;
  private:
  bool _internal_has_team() const;
  public:
  void clear_team();
  ::Team team() const;
  void set_team(::Team value);
  private:
  ::Team _internal_team() const;
  void _internal_set_team(::Team value);
  public:

  // @@protoc_insertion_point(class_scope:RobotId)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t id_;
    int team_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ssl_5fgc_5fcommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotId

// optional uint32 id = 1;
inline bool RobotId::_internal_has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RobotId::has_id() const {
  return _internal_has_id();
}
inline void RobotId::clear_id() {
  _impl_.id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t RobotId::_internal_id() const {
  return _impl_.id_;
}
inline uint32_t RobotId::id() const {
  // @@protoc_insertion_point(field_get:RobotId.id)
  return _internal_id();
}
inline void RobotId::_internal_set_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_ = value;
}
inline void RobotId::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:RobotId.id)
}

// optional .Team team = 2;
inline bool RobotId::_internal_has_team() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RobotId::has_team() const {
  return _internal_has_team();
}
inline void RobotId::clear_team() {
  _impl_.team_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::Team RobotId::_internal_team() const {
  return static_cast< ::Team >(_impl_.team_);
}
inline ::Team RobotId::team() const {
  // @@protoc_insertion_point(field_get:RobotId.team)
  return _internal_team();
}
inline void RobotId::_internal_set_team(::Team value) {
  assert(::Team_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.team_ = value;
}
inline void RobotId::set_team(::Team value) {
  _internal_set_team(value);
  // @@protoc_insertion_point(field_set:RobotId.team)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Team> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Team>() {
  return ::Team_descriptor();
}
template <> struct is_proto_enum< ::Division> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Division>() {
  return ::Division_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ssl_5fgc_5fcommon_2eproto
